version: 2

jobs:
  linux:
    docker:
      - image: letsspeak/pebble-ci:latest
    docker_layer_caching: true
    working_directory: ~/pebble
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test

  linux-release:
    docker:
      - image: letsspeak/pebble-ci:latest
    docker_layer_caching: true
    working_directory: ~/pebble
    steps:
      - checkout
      - run:
          name: Compile code with optimizations
          command: swift build -c release

workflows:
  version: 2
  build:
    jobs:
      - linux
      - linux-release

